/**
 * Dynamic Coding Question Generation + Deduplication.
 *
 * Questions are generated by the AI gateway against live context (resume
 * skills, JD skills, role, language, difficulty, history) and validated for
 * quality + duplicates before acceptance. When the AI gateway is offline a
 * deterministic template composer produces varied problems (across many
 * topics) so the feature never silently degrades to a tiny fixed list.
 */

import { createHash } from 'crypto';
import { createGatewaySession, sendGatewayMessage } from './aiGateway';
import { detectConcepts, normalizeConcepts, sharesConcept } from './codingConcepts';

export type Difficulty = 'Easy' | 'Medium' | 'Hard';

export const CODING_TOPICS = [
  'arrays', 'strings', 'hash maps', 'sorting', 'searching', 'linked lists',
  'stacks', 'queues', 'trees', 'graphs', 'recursion', 'dynamic programming',
  'sql', 'practical programming', 'debugging', 'api', 'frontend', 'backend',
];

export interface CodingExample {
  input: string;
  output: string;
  explanation?: string;
}

export interface CodingQuestion {
  id: string;
  title: string;
  problemStatement: string;
  constraints: string[];
  inputFormat: string;
  outputFormat: string;
  examples: CodingExample[];
  expectedComplexity: string;
  testCases: Array<{ stdin: string; expected: string }>;
  hiddenTestCases: Array<{ stdin: string; expected: string }>;
  language: string;
  difficulty: Difficulty;
  topic: string;
  /** Canonical concept slugs (used for concept-level duplicate detection). */
  concepts: string[];
  questionHash: string;
  source: 'ai' | 'template';
  date: string;
}

export interface QuestionHistoryEntry {
  question: string;
  questionHash: string;
  difficulty: Difficulty;
  topic: string;
  language: string;
  source: string;
  date: string;
  interviewId?: string;
  concepts?: string[];
}

export interface GenerateQuestionInput {
  resumeSkills: string[];
  jdSkills: string[];
  role: string;
  language: string;
  difficulty: Difficulty;
  topic?: string;
  previous: QuestionHistoryEntry[];
  // ── Phase 5: expanded (compact) candidate/job/project/performance context ──
  /** Compact structured resume summary (summarizeResumeProfile output). */
  resumeProfile?: string;
  /** Compact structured JD summary (summarizeJdProfile output). */
  jdProfile?: string;
  /** Compact resume<->JD match summary (summarizeMatchReport output). */
  matchSummary?: string;
  /** Compact GitHub/project analysis summary (summarizeProjectProfile output). */
  projectProfile?: string;
  /** Raw-ish GitHub summary text when no structured profile exists. */
  githubSummary?: string;
  /** Canonical concepts the candidate failed on earlier questions. */
  failedConcepts?: string[];
  /** Canonical concepts the candidate has mastered. */
  masteredConcepts?: string[];
  /** Structured JD required/preferred skills for the <job_context> block. */
  jdRequiredSkills?: string[];
  jdPreferredSkills?: string[];
  /** Structured JD responsibilities. */
  jdResponsibilities?: string[];
}

// ──────────────────────────────────────────────────────────────
// Normalization + hashing + similarity
// ──────────────────────────────────────────────────────────────

export function normalizeQuestionText(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function questionHash(text: string): string {
  return createHash('sha1').update(normalizeQuestionText(text)).digest('hex').slice(0, 16);
}

export function jaccardSimilarity(a: string, b: string): number {
  const ta = new Set(normalizeQuestionText(a).split(' '));
  const tb = new Set(normalizeQuestionText(b).split(' '));
  if (ta.size === 0 || tb.size === 0) return 0;
  let inter = 0;
  for (const t of ta) if (tb.has(t)) inter += 1;
  return inter / (ta.size + tb.size - inter);
}

export function isDuplicate(question: string, history: QuestionHistoryEntry[]): { isDup: boolean; reason: string } {
  const q = normalizeQuestionText(question);
  if (!q) return { isDup: false, reason: 'empty' };
  const hash = questionHash(question);
  for (const h of history) {
    if (h.questionHash === hash) return { isDup: true, reason: 'Exact match with a previous question' };
    const sim = jaccardSimilarity(q, h.question);
    if (sim > 0.78) {
      return { isDup: true, reason: `Too similar to a previous question (${Math.round(sim * 100)}% overlap)` };
    }
  }
  return { isDup: false, reason: 'unique' };
}

/**
 * Phase 5 — concept-level duplicate detection. Two questions that share the
 * same canonical underlying pattern (e.g. both two-sum style hash-map pair
 * lookups) are rejected even when the wording is entirely different. Uses only
 * deterministic local concept metadata — no embedding API required.
 */
export function isConceptDuplicate(
  concepts: string[],
  history: QuestionHistoryEntry[],
): { isDup: boolean; reason: string } {
  const normalized = normalizeConcepts(concepts);
  if (normalized.length === 0) return { isDup: false, reason: 'no concepts' };
  for (const h of history) {
    const prev = h.concepts && h.concepts.length ? h.concepts : [];
    if (!prev.length) continue;
    if (sharesConcept(normalized, prev)) {
      return { isDup: true, reason: `Same underlying pattern as a previous question (${normalized.slice(0, 3).join(', ')})` };
    }
  }
  return { isDup: false, reason: 'concepts unique' };
}

// ──────────────────────────────────────────────────────────────
// Deterministic template composer (offline fallback)
// ──────────────────────────────────────────────────────────────

const TEMPLATES: Array<{
  topic: string;
  title: (v: string) => string;
  build: (v: string) => { statement: string; constraints: string[]; inputFormat: string; outputFormat: string; examples: CodingExample[]; complexity: string; testCases: Array<{ stdin: string; expected: string }> };
}> = [
  {
    topic: 'arrays',
    title: (v) => `Find the pair with target sum ${v}`,
    build: (v) => {
      const target = 9 + (Number(v) % 5);
      const cases = [
        { stdin: '4 7\n2 4 3 3', expected: '1 3' },
        { stdin: '5 9\n2 7 4 5 1', expected: '0 1' },
        { stdin: '3 6\n3 2 4', expected: '1 2' },
        { stdin: '4 14\n1 5 9 2', expected: '0 2' },
      ];
      return {
        statement: `Given an array of integers and a target value ${target}, return the 0-based indices of the two numbers that add up to the target. There is guaranteed to be exactly one solution.`,
        constraints: ['2 ≤ n ≤ 10^4', '-10^9 ≤ nums[i] ≤ 10^9', 'Exactly one valid answer exists'],
        inputFormat: 'First line: n target. Second line: n space-separated integers.',
        outputFormat: 'Two 0-based indices, space-separated.',
        examples: [{ input: '4 7\n2 4 3 3', output: '1 3', explanation: 'nums[1] + nums[3] = 4 + 3 = 7' }],
        complexity: 'Expected O(n) time using a hash map, O(n) space.',
        testCases: cases,
      };
    },
  },
  {
    topic: 'strings',
    title: () => 'Valid parentheses sequence',
    build: () => ({
      statement: `Given a string containing only the characters '(', ')', '{', '}', '[' and ']', determine whether the input string is valid. A string is valid if open brackets are closed by the same type of bracket in the correct order.`,
      constraints: ['1 ≤ s.length ≤ 10^4'],
      inputFormat: 'A single line containing the bracket string.',
      outputFormat: 'true if valid, false otherwise.',
      examples: [
        { input: '()[]{}', output: 'true' },
        { input: '([)]', output: 'false' },
      ],
      complexity: 'Expected O(n) time using a stack, O(n) space.',
      testCases: [
        { stdin: '()[]{}', expected: 'true' },
        { stdin: '([)]', expected: 'false' },
        { stdin: '((()))', expected: 'true' },
        { stdin: '(]', expected: 'false' },
        { stdin: '', expected: 'true' },
      ],
    }),
  },
  {
    topic: 'sorting',
    title: () => 'Merge two sorted arrays in place',
    build: () => ({
      statement: `Given two sorted integer arrays nums1 and nums2, merge them into nums1 in sorted order. nums1 has enough space at the end to hold all elements.`,
      constraints: ['0 ≤ m, n ≤ 200', '1 ≤ m + n ≤ 200', 'Values fit in 32-bit integers'],
      inputFormat: 'First line: m n. Second line: m integers for nums1 followed by n zeros. Third line: n integers for nums2.',
      outputFormat: 'The merged array in sorted order, space-separated.',
      examples: [{ input: '3 3\n1 2 3 0 0 0\n2 5 6', output: '1 2 2 3 5 6' }],
      complexity: 'Expected O(m + n) time, O(1) extra space (merge from the end).',
      testCases: [
        { stdin: '3 3\n1 2 3 0 0 0\n2 5 6', expected: '1 2 2 3 5 6' },
        { stdin: '1 1\n1 0\n2', expected: '1 2' },
        { stdin: '0 1\n0\n1', expected: '1' },
        { stdin: '2 2\n1 4 0 0\n2 3', expected: '1 2 3 4' },
      ],
    }),
  },
  {
    topic: 'linked lists',
    title: () => 'Reverse a linked list iteratively',
    build: () => ({
      statement: `Given the head of a singly linked list, reverse the list and return its new head. Implement it iteratively.`,
      constraints: ['0 ≤ n ≤ 5000', '-5000 ≤ Node.val ≤ 5000'],
      inputFormat: 'First line: n. Second line: n integers (head values).',
      outputFormat: 'The reversed list values, space-separated.',
      examples: [{ input: '5\n1 2 3 4 5', output: '5 4 3 2 1' }],
      complexity: 'Expected O(n) time, O(1) extra space.',
      testCases: [
        { stdin: '5\n1 2 3 4 5', expected: '5 4 3 2 1' },
        { stdin: '2\n1 2', expected: '2 1' },
        { stdin: '1\n7', expected: '7' },
        { stdin: '0\n', expected: '' },
      ],
    }),
  },
  {
    topic: 'hash maps',
    title: () => 'First non-repeating character',
    build: () => ({
      statement: `Given a string s, find the first non-repeating character and return its 0-based index. If it does not exist, return -1.`,
      constraints: ['1 ≤ s.length ≤ 10^5', 's consists of lowercase English letters'],
      inputFormat: 'A single line: the string.',
      outputFormat: 'The index of the first non-repeating character, or -1.',
      examples: [
        { input: 'leetcode', output: '0' },
        { input: 'loveleetcode', output: '2' },
      ],
      complexity: 'Expected O(n) time using a frequency hash map, O(1) space (26 letters).',
      testCases: [
        { stdin: 'leetcode', expected: '0' },
        { stdin: 'loveleetcode', expected: '2' },
        { stdin: 'aabb', expected: '-1' },
        { stdin: 'abcabcde', expected: '6' },
      ],
    }),
  },
  {
    topic: 'dynamic programming',
    title: () => 'Climbing stairs',
    build: () => ({
      statement: `You are climbing a staircase with n steps. Each time you can either climb 1 or 2 steps. In how many distinct ways can you reach the top?`,
      constraints: ['1 ≤ n ≤ 45'],
      inputFormat: 'A single integer n.',
      outputFormat: 'The number of distinct ways.',
      examples: [{ input: '3', output: '3', explanation: '1+1+1, 1+2, 2+1' }],
      complexity: 'Expected O(n) time with DP or O(1) space with the Fibonacci recurrence.',
      testCases: [
        { stdin: '2', expected: '2' },
        { stdin: '3', expected: '3' },
        { stdin: '4', expected: '5' },
        { stdin: '10', expected: '89' },
      ],
    }),
  },
  {
    topic: 'stacks',
    title: () => 'Evaluate reverse polish notation',
    build: () => ({
      statement: `Evaluate the value of an arithmetic expression in Reverse Polish Notation. Valid operators are +, -, *, /. Division truncates toward zero.`,
      constraints: ['1 ≤ tokens.length ≤ 10^4', 'Operands and results fit in 32-bit integers'],
      inputFormat: 'A single line: tokens separated by spaces.',
      outputFormat: 'The integer result.',
      examples: [{ input: '2 1 + 3 *', output: '9', explanation: '((2 + 1) * 3)' }],
      complexity: 'Expected O(n) time using a stack, O(n) space.',
      testCases: [
        { stdin: '2 1 + 3 *', expected: '9' },
        { stdin: '4 13 5 / +', expected: '6' },
        { stdin: '3 4 + 2 * 7 /', expected: '2' },
      ],
    }),
  },
  {
    topic: 'graphs',
    title: () => 'Course schedule cycle detection',
    build: () => ({
      statement: `There are numCourses courses labelled 0..numCourses-1. Given prerequisites where [a, b] means b must be taken before a, return true if you can finish all courses (no cycle exists in the graph).`,
      constraints: ['1 ≤ numCourses ≤ 2000', '0 ≤ prerequisites.length ≤ 5000'],
      inputFormat: 'First line: numCourses n. Second line: number of prerequisites m. Next m lines: a b.',
      outputFormat: 'true or false.',
      examples: [{ input: '2 2\n1 0\n0 1', output: 'false' }],
      complexity: 'Expected O(V + E) time with DFS/Kahn (topological sort).',
      testCases: [
        { stdin: '2 1\n1 0', expected: 'true' },
        { stdin: '2 2\n1 0\n0 1', expected: 'false' },
        { stdin: '4 4\n1 0\n2 0\n3 1\n3 2', expected: 'true' },
      ],
    }),
  },
  {
    topic: 'sql',
    title: () => 'Top earners by department',
    build: () => ({
      statement: `You are given a table employees(id, name, salary, department). Write a SQL query that returns, for each department, the name of the employee with the highest salary.`,
      constraints: ['You may assume each department has at most one top earner'],
      inputFormat: 'Not applicable — write SQL against the employees table.',
      outputFormat: 'Columns: department, name, salary.',
      examples: [{ input: 'dept A: Alice 5000, Bob 4000', output: 'A, Alice, 5000' }],
      complexity: 'Expected O(n) with a window function (ROW_NUMBER) or a correlated subquery.',
      testCases: [
        { stdin: '', expected: '' },
      ],
    }),
  },
  {
    topic: 'debugging',
    title: () => 'Find the bug: off-by-one sum',
    build: () => ({
      statement: `A candidate wrote a function that sums the numbers from 1 to n. It returns wrong results for some inputs. Find and fix the bug in the provided code.`,
      constraints: ['1 ≤ n ≤ 10^5'],
      inputFormat: 'A single integer n.',
      outputFormat: 'The correct sum 1 + 2 + ... + n.',
      examples: [{ input: '5', output: '15' }],
      complexity: 'Expected O(1) with the closed-form formula or O(n) with a loop.',
      testCases: [
        { stdin: '5', expected: '15' },
        { stdin: '10', expected: '55' },
        { stdin: '1', expected: '1' },
        { stdin: '100', expected: '5050' },
      ],
    }),
  },
  {
    topic: 'api',
    title: () => 'Build a rate-limited key-value store API',
    build: () => ({
      statement: `Design a REST API for a key-value store with GET /kv/:key and PUT /kv/:key, backed by an in-memory map. Add rate limiting: a single client may issue at most 5 requests per second.`,
      constraints: ['Keys ≤ 128 chars', 'Values ≤ 4096 chars'],
      inputFormat: 'Not applicable — API design task.',
      outputFormat: 'HTTP status codes + JSON bodies.',
      examples: [{ input: 'PUT /kv/a → 200', output: 'GET /kv/a → value' }],
      complexity: 'Expected O(1) per operation.',
      testCases: [],
    }),
  },
  {
    topic: 'trees',
    title: () => 'Maximum depth of a binary tree',
    build: () => ({
      statement: `Given the root of a binary tree, return its maximum depth. A binary tree's depth is the number of nodes along the longest path from the root to the farthest leaf.`,
      constraints: ['0 ≤ number of nodes ≤ 10^4'],
      inputFormat: 'Level-order traversal with null markers (write code, not I/O).',
      outputFormat: 'The maximum depth integer.',
      examples: [{ input: 'root [3,9,20,null,null,15,7]', output: '3' }],
      complexity: 'Expected O(n) time using BFS or DFS recursion.',
      testCases: [],
    }),
  },
  {
    topic: 'frontend',
    title: () => 'Debounced search input component',
    build: () => ({
      statement: `Implement a React (or vanilla) search input that debounces its onChange by 300ms and calls a fetchResults(query) callback only after the user stops typing. Show a loading indicator while fetching.`,
      constraints: ['Must cancel stale requests', 'Must handle rapid typing correctly'],
      inputFormat: 'Not applicable — component implementation task.',
      outputFormat: 'Working component with debounce.',
      examples: [{ input: 'Typing "React" quickly', output: 'One fetch after 300ms idle' }],
      complexity: 'Expected O(1) per keystroke (timer reset).',
      testCases: [],
    }),
  },
];

function pick(variantSeed: string): number {
  let h = 0;
  for (const c of variantSeed) h = (h * 31 + c.charCodeAt(0)) % 100000;
  return h;
}

function templateQuestion(language: string, difficulty: Difficulty, topic: string, seed: string): CodingQuestion {
  const topics = topic ? [topic] : CODING_TOPICS;
  const idx = pick(seed) % TEMPLATES.length;
  const tpl = TEMPLATES.find((t) => t.topic === topics.find((tp) => t.topic === tp)) || TEMPLATES[idx];
  const variant = String((pick(seed + 'x') % 90) + 10);
  const built = tpl.build(variant);
  const title = tpl.title(variant);
  const questionText = `${title}. ${built.statement} ${built.constraints.join(' ')}`;
  return {
    id: `tpl-${questionHash(questionText)}`,
    title,
    problemStatement: built.statement,
    constraints: built.constraints,
    inputFormat: built.inputFormat,
    outputFormat: built.outputFormat,
    examples: built.examples,
    expectedComplexity: built.complexity,
    testCases: built.testCases.slice(0, 2),
    hiddenTestCases: built.testCases.slice(2),
    language,
    difficulty,
    topic: tpl.topic,
    concepts: detectConcepts(title, built.statement),
    questionHash: questionHash(questionText),
    source: 'template',
    date: new Date().toISOString(),
  };
}

// ──────────────────────────────────────────────────────────────
// AI generation + validation
// ──────────────────────────────────────────────────────────────

function parseGeneratedQuestion(raw: string): Partial<CodingQuestion> | null {
  const cleaned = raw.trim().replace(/^```(json)?|```$/g, '').trim();
  const match = cleaned.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}

function validateQuestion(q: Partial<CodingQuestion>): q is CodingQuestion {
  return Boolean(
    typeof q.title === 'string' && q.title.trim() &&
    typeof q.problemStatement === 'string' && q.problemStatement.trim().length > 40 &&
    Array.isArray(q.constraints) &&
    typeof q.inputFormat === 'string' &&
    typeof q.outputFormat === 'string' &&
    Array.isArray(q.examples) && Array.isArray(q.testCases) &&
    typeof q.language === 'string' &&
    ['Easy', 'Medium', 'Hard'].includes(q.difficulty as string),
  );
}

function finalizeQuestion(q: Partial<CodingQuestion>, input: GenerateQuestionInput, topic: string): CodingQuestion {
  const questionText = `${q.title}. ${q.problemStatement} ${q.inputFormat} ${q.outputFormat}`;
  const hidden = Array.isArray(q.hiddenTestCases) && q.hiddenTestCases.length ? q.hiddenTestCases : [];
  const visible = Array.isArray(q.testCases) ? q.testCases : [];
  const concepts = normalizeConcepts(
    Array.isArray(q.concepts) ? q.concepts : detectConcepts(q.title || '', q.problemStatement || ''),
  );
  return {
    id: `ai-${questionHash(questionText)}`,
    title: q.title!.trim(),
    problemStatement: q.problemStatement!.trim(),
    constraints: Array.isArray(q.constraints) ? q.constraints.map((c: unknown) => String(c)).slice(0, 8) : [],
    inputFormat: q.inputFormat!.trim(),
    outputFormat: q.outputFormat!.trim(),
    examples: Array.isArray(q.examples) ? q.examples.map((e: any) => ({ input: String(e?.input ?? ''), output: String(e?.output ?? ''), explanation: e?.explanation ? String(e.explanation) : undefined })).slice(0, 3) : [],
    expectedComplexity: typeof q.expectedComplexity === 'string' ? q.expectedComplexity : '',
    testCases: visible.slice(0, 3).map((t: any) => ({ stdin: String(t?.stdin ?? t?.input ?? ''), expected: String(t?.expected ?? t?.output ?? '') })),
    hiddenTestCases: hidden.slice(0, 4).map((t: any) => ({ stdin: String(t?.stdin ?? t?.input ?? ''), expected: String(t?.expected ?? t?.output ?? '') })),
    language: q.language!.trim() || input.language,
    difficulty: q.difficulty as Difficulty,
    topic: q.topic || topic,
    concepts,
    questionHash: questionHash(questionText),
    source: 'ai',
    date: new Date().toISOString(),
  };
}

async function generateWithAI(input: GenerateQuestionInput, topic: string, attempt: number): Promise<CodingQuestion> {
  const session = await createGatewaySession('Coding question generator');
  if (session.fromMock) {
    throw new Error('mock');
  }

  const skillContext = [
    ...(input.resumeSkills.length ? [`Candidate skills: ${input.resumeSkills.slice(0, 25).join(', ')}`] : []),
    ...(input.jdSkills.length ? [`Role required skills: ${input.jdSkills.slice(0, 25).join(', ')}`] : []),
  ].join('\n');

  const prevBlock = input.previous.length
    ? input.previous.slice(-8).map((p, i) => `${i + 1}. ${p.question}`).join('\n')
    : 'none';

  // ── Phase 5: optional compact context blocks (resume/JD/match/project/performance) ──
  const resumeBlock = input.resumeProfile
    ? `<candidate_context>\n${truncateForPrompt(input.resumeProfile, 1800)}\n</candidate_context>`
    : null;

  const jobBlock = buildJobContextBlock(input);

  const projectBlock = (input.projectProfile || input.githubSummary)
    ? `<project_context>\n${truncateForPrompt(input.projectProfile || input.githubSummary || '', 1500)}\n</project_context>`
    : null;

  const perfBlock =
    input.failedConcepts?.length || input.masteredConcepts?.length
      ? `<performance_context>\n${[
          input.failedConcepts?.length ? `Concepts the candidate struggled with earlier: ${input.failedConcepts.slice(0, 10).join(', ')}.` : '',
          input.masteredConcepts?.length ? `Concepts the candidate already mastered: ${input.masteredConcepts.slice(0, 10).join(', ')}.` : '',
          'Tailor the problem to strengthen the struggled concepts when possible, without repeating them verbatim.',
        ].filter(Boolean).join('\n')}\n</performance_context>`
      : null;

  const prompt = [
    `You are a senior coding interviewer generating a fresh coding problem for a live mock interview.`,
    `Role: ${input.role}`,
    `Language: ${input.language}`,
    `Difficulty: ${input.difficulty}`,
    `Topic to target: ${topic}`,
    ``,
    skillContext,
    ...(resumeBlock ? ['', resumeBlock] : []),
    ...(jobBlock ? ['', jobBlock] : []),
    ...(projectBlock ? ['', projectBlock] : []),
    ...(perfBlock ? ['', perfBlock] : []),
    ``,
    `<questions_already_asked>`,
    prevBlock,
    `</questions_already_asked>`,
    ``,
    `Generate an original ${input.difficulty.toLowerCase()} coding problem in "${input.language}".`,
    `- Do NOT repeat or trivially reword any question in <questions_already_asked>.`,
    `- Do NOT reuse the same underlying algorithm as any earlier question (e.g. two different two-sum/hash-map-pair problems are still duplicates).`,
    `- It must be practical and solvable in a 30-45 minute voice interview.`,
    `- Weave in the candidate's actual stack from <candidate_context>/<project_context> where natural (e.g. React/Vite, Node/Express, PostgreSQL), but keep the core a solvable algorithm/data-structure problem.`,
    ...(input.failedConcepts?.length
      ? [`- If a concept listed in <performance_context> fits the ${topic} topic, prefer it as the central technique.`]
      : []),
    ``,
    `Return exactly one JSON object, no markdown, with this schema:`,
    `{"title":"<short title>","problemStatement":"<full problem, markdown allowed>","constraints":["<...>"],"inputFormat":"<how stdin is read>","outputFormat":"<what stdout prints>","examples":[{"input":"<stdin>","output":"<stdout>","explanation":"<optional>"}],"expectedComplexity":"<time+space>","concepts":["<3-5 canonical technique tags, e.g. hash map, sliding window, dynamic programming, graph traversal, prefix sum, stack, greedy, two pointers, binary search, string parsing, math>"],"testCases":[{"stdin":"<exact stdin>","expected":"<exact expected stdout>"}],"hiddenTestCases":[{"stdin":"<exact stdin>","expected":"<exact expected stdout>"}],"language":"${input.language}","difficulty":"${input.difficulty}","topic":"${topic}"}`,
    ``,
    `Rules for test cases: expected values MUST be exact stdout strings (trimmed), deterministic, and self-contained per stdin. Provide at least 3 visible and 3 hidden test cases (skip hiddenTestCases for SQL/frontend/API/design tasks).`,
  ].join('\n');

  const completion = await sendGatewayMessage(session.gatewaySessionId, prompt);
  const parsed = parseGeneratedQuestion(completion.text);
  if (!parsed || !validateQuestion(parsed)) {
    throw new Error('AI returned an invalid coding question');
  }
  return finalizeQuestion(parsed, input, topic);
}

function truncateForPrompt(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max)}… (truncated)`;
}

function buildJobContextBlock(input: GenerateQuestionInput): string | null {
  const jd = input.jdProfile;
  const lines: string[] = [];
  if (input.jdRequiredSkills?.length) lines.push(`Required skills: ${input.jdRequiredSkills.slice(0, 15).join(', ')}`);
  if (input.jdPreferredSkills?.length) lines.push(`Preferred skills: ${input.jdPreferredSkills.slice(0, 15).join(', ')}`);
  if (input.jdResponsibilities?.length) lines.push(`Responsibilities: ${input.jdResponsibilities.slice(0, 6).join('; ')}`);
  if (lines.length) {
    return `<job_context>\n${lines.join('\n')}${jd ? `\n${truncateForPrompt(jd, 1200)}` : ''}\n</job_context>`;
  }
  if (input.matchSummary) {
    return `<job_context>\n${truncateForPrompt(input.matchSummary, 1200)}\n</job_context>`;
  }
  return jd ? `<job_context>\n${truncateForPrompt(jd, 1200)}\n</job_context>` : null;
}

// ──────────────────────────────────────────────────────────────
// Public API
// ──────────────────────────────────────────────────────────────

// Design-style topics (API / frontend / trees) have no stdin/stdout test
// harness, so a generated question on those topics can't be verified in the
// Judge0 workspace. They stay available when explicitly requested, but are
// excluded from random selection so generated problems are always runnable.
const NON_EXECUTABLE_TOPICS = new Set(['api', 'frontend', 'trees']);
const EXECUTABLE_TOPICS = CODING_TOPICS.filter((t) => !NON_EXECUTABLE_TOPICS.has(t));

export async function generateCodingQuestion(input: GenerateQuestionInput): Promise<{ question: CodingQuestion; fromMock: boolean; attempts: number; dupRejected: number }> {
  const topics = input.topic
    ? [input.topic]
    : EXECUTABLE_TOPICS.filter((t) => (input.resumeSkills.length + input.jdSkills.length) === 0 || t !== 'sql' || input.jdSkills.some((s) => s.toLowerCase() === 'sql'));
  let dupRejected = 0;
  let lastError: Error | null = null;

  for (let attempt = 0; attempt < 3; attempt++) {
    const topic = topics[(attempt + (input.previous.length || 0)) % topics.length];
    try {
      const question = await generateWithAI(input, topic, attempt);
      const dup = isDuplicate(`${question.title} ${question.problemStatement}`, input.previous);
      if (dup.isDup) {
        dupRejected += 1;
        continue;
      }
      const conceptDup = isConceptDuplicate(question.concepts, input.previous);
      if (conceptDup.isDup) {
        dupRejected += 1;
        continue;
      }
      return { question, fromMock: false, attempts: attempt + 1, dupRejected };
    } catch (err) {
      lastError = err as Error;
      if ((err as Error).message === 'mock') break;
    }
  }

  // Offline / repeated failure → deterministic template generation
  const seed = `${input.language}:${input.difficulty}:${input.role}:${input.previous.length}`;
  const pool = topics.length ? topics : EXECUTABLE_TOPICS;
  const topic = pool[(input.previous.length || pick(seed)) % pool.length];
  let question = templateQuestion(input.language, input.difficulty, topic, seed);
  let guard = 0;
  while (isDuplicate(`${question.title} ${question.problemStatement}`, input.previous).isDup && guard < 8) {
    question = templateQuestion(input.language, input.difficulty, pool[guard % pool.length], seed + guard);
    guard += 1;
  }
  return { question, fromMock: true, attempts: 1, dupRejected };
}
